no_permission: "&cYou don't have permission to perform this command."
player_only: "&cOnly players can execute this command."
player_not_found: "&cPlayer not found."
usage_gamemode: "&cUsage: /gamemode <type> [player]"
invalid_gamemode: "&cInvalid gamemode type."
gamemode_set: "&aYour gamemode has been set to {mode}."
gamemode_set_other: "&aYou have set {player}'s gamemode to {mode}."
usage_openinv: "&cUsage: /openinv <player>"
no_item_in_hand: "&cYou must be holding an item."
item_repaired: "&aYour item has been repaired."
tpa_request_sent: "&aTeleport request sent to {player}."
tpa_request_received: "&a{player} has requested to teleport to you. Type /tpaccept or /tpdeny."
no_tpa_request: "&cYou have no pending teleport requests."
tpa_request_accepted: "&aTeleport request accepted."
tpa_request_acceptor: "&aYou have accepted the teleport request."
tpa_request_denied: "&cTeleport request denied."
tpa_request_denied_sender: "&cYou have denied the teleport request."
godmode_enabled: "&aGod mode enabled."
godmode_disabled: "&cGod mode disabled."
godmode_enabled_other: "&aGod mode enabled for {player}."
godmode_disabled_other: "&cGod mode disabled for {player}."